In [36]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})

df.info()
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)
print("Data frame with corrected FlightNumber")
print(df)

Tempdf = df['From_To'].str.split('_', 1, expand=True).rename(columns={0:'From', 1:'To'})
print("Temp Data frame with the split of From and To")
print(Tempdf)

print("capitalisation of the city names")
Tempdf['From'] = Tempdf['From'].str.capitalize()
Tempdf['To'] = Tempdf['To'].str.capitalize()
print(Tempdf)

print("Joining Temp Data frame with the original")
df = df.drop(['From_To'], axis=1)
df = df.join(Tempdf)
print(df)

print("Expand the Series of lists into a DataFrame named delays")
delay = df['RecentDelays'].apply(pd.Series)
delays = delay.rename(columns = lambda x : 'delay_' + str(x))
print(delays)

print("Replace the unwanted RecentDelays column in d with delays")
df = df.drop(['RecentDelays'], axis=1)
df = df.join(delays)
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
Airline         5 non-null object
FlightNumber    3 non-null float64
From_To         5 non-null object
RecentDelays    5 non-null object
dtypes: float64(1), object(3)
memory usage: 240.0+ bytes
Data frame with corrected FlightNumber
               Airline  FlightNumber           From_To  RecentDelays
0               KLM(!)         10045      LoNDon_paris      [23, 47]
1    <Air France> (12)         10055      MAdrid_miLAN            []
2  (British Airways. )         10065  londON_StockhOlm  [24, 43, 87]
3       12. Air France         10075    Budapest_PaRis          [13]
4          "Swiss Air"         10085   Brussels_londOn      [67, 32]
Temp Data frame with the split of From and To
       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn
capitalisation of the city names
       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London
Joining Temp Data frame with the original
               Airline  FlightNumber  RecentDelays      From         To
0               KLM(!)         10045      [23, 47]    London      Paris
1    <Air France> (12)         10055            []    Madrid      Milan
2  (British Airways. )         10065  [24, 43, 87]    London  Stockholm
3       12. Air France         10075          [13]  Budapest      Paris
4          "Swiss Air"         10085      [67, 32]  Brussels     London
Expand the Series of lists into a DataFrame named delays
   delay_0  delay_1  delay_2
0     23.0     47.0      NaN
1      NaN      NaN      NaN
2     24.0     43.0     87.0
3     13.0      NaN      NaN
4     67.0     32.0      NaN
Replace the unwanted RecentDelays column in df with delays
               Airline  FlightNumber      From         To  delay_0  delay_1  \
0               KLM(!)         10045    London      Paris     23.0     47.0
1    <Air France> (12)         10055    Madrid      Milan      NaN      NaN
2  (British Airways. )         10065    London  Stockholm     24.0     43.0
3       12. Air France         10075  Budapest      Paris     13.0      NaN
4          "Swiss Air"         10085  Brussels     London     67.0     32.0

   delay_2
0      NaN
1      NaN
2     87.0
3      NaN
4      NaN